### ISSUE TITLE
Port to a React/React Native app

### ISSUE THREAD

**Issue by gauravkg15** [MoralCode/ClassClock#15]
Awesome idea and app!

How do you feel about porting this to a React app? Would be great to use the feature-set the ecosystem offers + the same components/architecture could be used to port to iOS/Android native applications via React Native

**Comment by MoralCode** [comment]
Work is already being done on the `migration` branch to port ClassClock from vanilla JS to React!

**Comment by MoralCode** [comment]
This is now complete as of 6ab34a17903ac450810e8a4858582a4c042c9660
