### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by cbass2020** [MoralCode/ClassClock#5]
[ ] yes i have checked to make sure that there are no other feature requests for this idea that have already been submitted.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cbass2020** [comment]
Add if its an A or B day and what the next day will be

**Comment by MoralCode** [comment]
Thank you for your request. Detection of whether it is an A or B day is a feature that has been requested multiple times already and is planed for a later version (hopefully version 2 but this isn't set in stone yet).
