### ISSUE TITLE
"Your next class period is" displays current day's first period instead of next day's first period

### ISSUE THREAD

**Issue by nbd9** [MoralCode/ClassClock#8]
**Describe the bug**
"Your next class period is:" displays current day's first period instead of next day's first period

**To Reproduce**
1. Go to the homepage on finals schedule.
2. Look at the "your next class period" section.

**Expected behavior**
(On Wed, Jan 23rd)
Your next class period is A3 Final.

**Comment by MoralCode** [comment]
This occurred after school was out for the day right?

**Comment by MoralCode** [comment]
I don’t think we need this feature to work across school days. It’s not that useful overall and is only really meant to be used during the school day.

**Comment by MoralCode** [comment]
im pretty sure this has been fixed since v1.0
